export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS"
export const USER_REGISTRATION_REQUEST = "USER_REGISTRATION_REQUEST"
export const USER_REGISTRATION_FAILURE = "USER_REGISTRATION_FAILURE"
export const UPDATE_USER_REGISTRATION = "UPDATE_USER_REGISTRATION"